SELECT * FROM CIDADE;

SELECT NOME FROM CIDADE;

SELECT nome from TURMA WHERE dataInicio > DATE('now');

SELECT NOME FROM INSTRUTOR WHERE dataNascimento > '1980-01-01';

SELECT AVG(idade) FROM ALUNO;

SELECT AVG(numeroAlunos) FROM TURMA;

SELECT COUNT (*) FROM INSTRUTOR;

SELECT MAX(idade) FROM INSTRUTOR;

SELECT MIN(numeroAlunos) FROM TURMA;

SELECT MIN(numeroMatriculas) 
FROM (
    SELECT COUNT(MATRICULA.aluno_id) AS numeroMatriculas 
    FROM TURMA
    INNER JOIN MATRICULA ON TURMA.id = MATRICULA.turma_id
    GROUP BY TURMA.id
);

SELECT CIDADE.nome, AVG(ALUNO.idade)
FROM ALUNO
INNER JOIN ENDERECO ON ALUNO.endereco_id = ENDERECO.id
INNER JOIN CIDADE ON ENDERECO.cidade_id = CIDADE.id
GROUP BY CIDADE.nome;

SELECT CIDADE.nome, COUNT (*)
FROM INSTRUTOR
INNER JOIN ENDERECO ON INSTRUTOR.endereco_id = ENDERECO.id
INNER JOIN CIDADE ON ENDERECO.cidade_id = CIDADE.id
GROUP BY CIDADE.nome;

SELECT INSTITUICAO.nome, CIDADE.nome
FROM INSTITUICAO
INNER JOIN CIDADE ON INSTITUICAO.cidade_id = CIDADE.id;

SELECT ALUNO.nome
FROM ALUNO
INNER JOIN MATRICULA ON MATRICULA.aluno_id = ALUNO.id
INNER JOIN TURMA ON TURMA.id = MATRICULA.turma_id AND turma.id = 4;

SELECT ALUNO.nome, TELEFONE.numero
FROM ALUNO
INNER JOIN TELEFONE ON TELEFONE.aluno_id = ALUNO.id;

SELECT ATIVIDADE.nome, TURMA.data_inicio
FROM ATIVIDADE
INNER JOIN TURMA ON ATIVIDADE.turma_id = TURMA.id

SELECT TITULACAO.titulo, INSTRUTOR.nome, INSTITUICAO.nome
FROM TITULACAO
INNER JOIN INSTRUTOR ON TITULACAO.instrutor_id = INSTRUTOR.id
INNER JOIN INSTITUICAO on TITULACAO.instituicao_id = INSTITUICAO.id
ORDER by INSTRUTOR.nome

SELECT ALUNO.nome
FROM ALUNO
INNER JOIN MATRICULA ON ALUNO.id = MATRICULA.aluno_id
GROUP BY ALUNO.id, ALUNO.nome
HAVING COUNT(MATRICULA.turma_id) > 1;

SELECT INSTRUTOR.nome, COUNT (TURMA.id) 
FROM INSTRUTOR
INNER JOIN TURMA ON INSTRUTOR.id = TURMA.aluno_monitor
GROUP BY INSTRUTOR.id;