CREATE TABLE INSTITUICAO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME TEXT
);

CREATE TABLE TIPO_TITULACAO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	DESCRICAO TEXT
);

CREATE TABLE ATIVIDADE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME TEXT
);

CREATE TABLE CIDADE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME TEXT
);

CREATE TABLE TITULACAO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TITULO TEXT,
	TIPO_ID INTEGER,
	DATA_CONCLUSAO TEXT,
	INSTITUICAO_ID INTEGER,
	FOREIGN KEY (TIPO_ID) REFERENCES TIPO_TITULACAO(ID),
	FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO(ID)
);

CREATE TABLE ENDERECO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	RUA TEXT,
	NUMERO INTEGER,
	CIDADE_ID INTEGER,
	FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE(ID)
);

CREATE TABLE INSTRUTOR(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	ENDERECO_ID INTEGER,
	DATA_NASC TEXT,
	RG INTEGER,
	FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);

ALTER TABLE TITULACAO
ADD COLUMN INSTRUTOR_ID INTEGER REFERENCES INSTRUTOR(ID);

CREATE TABLE TELEFONE(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NUMERO INTEGER,
	DDD INTEGER,
	INSTRUTOR_ID INTEGER,
	FOREIGN KEY (INSTRUTOR_ID) REFERENCES INSTRUTOR(ID)
);

CREATE TABLE ALUNO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME TEXT,
	ENDERECO_ID INTEGER,
	DATA_NASC TEXT,
	ALTURA REAL,
	PESO REAL,	
	FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);

CREATE TABLE TURMA(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CAPACIDADE INTEGER,
	DATA_INICIO TEXT,
	DATA_FIM TEXT,
	ATIVIDADE_ID INTEGER,
	HORA_INICIO TEXT,
	HORA_FIM TEXT,
	MONITOR_ID INTEGER,
	FOREIGN KEY (ATIVIDADE_ID) REFERENCES ATIVIDADE(ID),
	FOREIGN KEY (MONITOR_ID) REFERENCES ALUNO(ID)
);

CREATE TABLE MATRICULA(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	ALUNO_ID INTEGER,
	TURMA_ID INTEGER,
	DATA_MATRICULA TEXT,
	FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID),
	FOREIGN KEY (TURMA_ID) REFERENCES TURMA(ID)
);

CREATE TABLE PRESENCA(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	MATRICULA_ID INTEGER,
	DATA_PRESENCA TEXT,
	PRESENTE INTEGER,
	FOREIGN KEY (MATRICULA_ID) REFERENCES MATRICULA(ID)
);