/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author felip
 */
public class NotePadView extends javax.swing.JFrame {

    /**
     * Creates new form NotePadView
     */
    public NotePadView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTxtArea = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloco de Notas");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setToolTipText("");
        jScrollPane.setViewportView(jTextArea);

        javax.swing.GroupLayout jPanelTxtAreaLayout = new javax.swing.GroupLayout(jPanelTxtArea);
        jPanelTxtArea.setLayout(jPanelTxtAreaLayout);
        jPanelTxtAreaLayout.setHorizontalGroup(
            jPanelTxtAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        jPanelTxtAreaLayout.setVerticalGroup(
            jPanelTxtAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        getContentPane().add(jMenuBar, java.awt.BorderLayout.CENTER);

        jMenuBar.setMaximumSize(new java.awt.Dimension(600, 50));
        jMenuBar.setMinimumSize(new java.awt.Dimension(600, 50));
        jMenuBar.setPreferredSize(new java.awt.Dimension(600, 50));

        jMenuFile.setText("File");
        jMenuFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuFile.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuItem1.setText("jMenuItem1");
        jMenuFile.add(jMenuItem1);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuEdit.setPreferredSize(new java.awt.Dimension(50, 50));
        jMenuBar.add(jMenuEdit);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotePadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotePadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotePadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotePadView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotePadView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelTxtArea;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
