package models;

public enum Status {
    REGISTRADO,
    EM_PREPARO,
    PRONTO_PARA_ENTREGA,
    PRONTO_PARA_RETIRADA,
    SAIU_PARA_ENTREGA,
    ENTREGUE,
    CANCELADO,
    REEMBOLSADO,
    AGUARDANDO_PAGAMENTO,
    PAGAMENTO_CONFIRMADO
}
